FROM gcc:latest
USER root
COPY ["C:/Users/Iago Leal/Desktop/TCC/TCC/SerialComApp/", "C:/Users/Iago Leal/Desktop/TCC/TCC/SerialComApp/"]
RUN mkdir -p C:/Users/Iago Leal/Desktop/TCC/TCC/SerialComApp/
WORKDIR C:/Users/Iago Leal/Desktop/TCC/TCC/SerialComApp/
RUN g++ -o serial_app interferometro_serial.cpp
CMD ["./serial_app"]

# FROM gcc:4.9
# COPY . /usr/src/myapp
# WORKDIR /usr/src/myapp
# RUN gcc -o myapp main.c
# CMD ["./myapp"]

# C:\Users\Iago Leal\Desktop\TCC\TCC8.0\SerialComApp\Teste
# docker build -t my-gcc-app .
# docker run -it --rm --name my-running-app my-gcc-app
# or docker run --rm -v "$PWD":C:/Users/Iago Leal/Desktop/TCC/Teste/ -w C:/Users/Iago Leal/Desktop/TCC/Teste/ gcc:latest g++ -o gccteste teste.cpp